services:
  db:
    image: mysql:8.0
    container_name: hms-mysql
    restart: always
    environment:
      MYSQL_DATABASE: hms
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: hms-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: "hospital-local-secret-key-2026-very-secure-123456"
      FRONTEND_URL: "http://localhost,http://localhost:5173"
      PORT: 8080
      SPRING_REDIS_HOST: localhost
      SPRING_REDIS_PORT: 6379
      RATELIMIT_AUTH_ACCOUNT_CAPACITY: 100
      RATELIMIT_AUTH_ACCOUNT_REFILL_MINUTES: 1
      RATELIMIT_AUTH_IP_CAPACITY: 100
      RATELIMIT_AUTH_IP_REFILL_MINUTES: 1
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: hms-frontend
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - backend

volumes:
  db-data:
