package com.hms.service.storage;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.mock.env.MockEnvironment;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * The storage layer, and the one thing it must never do: let a key point outside its own root.
 *
 * <p>Keys are generated by this class, so a key shaped like a path did not come from here. These
 * tests use a temporary directory -- nothing depends on a real server, a deployment path, or
 * anything existing on the machine running them.
 */
class LocalVpsClinicalDocumentStorageTest {

    @TempDir Path root;
    private LocalVpsClinicalDocumentStorage storage;

    @BeforeEach
    void setUp() {
        storage = new LocalVpsClinicalDocumentStorage(root.toString(), new MockEnvironment());
        storage.initialise();
    }

    private static InputStream bytes(String content) {
        return new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8));
    }

    @Test
    void aStoredDocumentCanBeReadBack() throws Exception {
        var stored = storage.store("h1", "p1", "pdf", bytes("report contents"), 15);

        assertThat(storage.exists(stored.storageKey())).isTrue();
        try (InputStream in = storage.load(stored.storageKey())) {
            assertThat(new String(in.readAllBytes(), StandardCharsets.UTF_8)).isEqualTo("report contents");
        }
        assertThat(stored.sizeBytes()).isEqualTo(15);
    }

    @Test
    void theKeyRevealsNothingAboutThePatient() {
        var stored = storage.store("h1", "p1", "pdf", bytes("x"), 1);

        assertThat(stored.storageKey())
                .as("no patient name, no original filename, nothing guessable")
                .doesNotContain("blood").doesNotContain("report").doesNotContain("Asha")
                .matches("h1/p1/[0-9a-f-]{36}[.]pdf");
    }

    @Test
    void twoUploadsOfTheSameFileDoNotCollide() {
        var first = storage.store("h1", "p1", "pdf", bytes("same"), 4);
        var second = storage.store("h1", "p1", "pdf", bytes("same"), 4);
        assertThat(first.storageKey()).isNotEqualTo(second.storageKey());
        assertThat(storage.exists(first.storageKey())).isTrue();
        assertThat(storage.exists(second.storageKey())).isTrue();
    }

    /** A half-written upload must never be left behind looking like a document. */
    @Test
    void nothingPartialSurvivesAFailedWrite() throws Exception {
        InputStream exploding = new InputStream() {
            @Override public int read() throws java.io.IOException {
                throw new java.io.IOException("connection dropped");
            }
        };

        assertThatThrownBy(() -> storage.store("h1", "p1", "pdf", exploding, 10))
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);

        try (var walk = Files.walk(root)) {
            assertThat(walk.filter(Files::isRegularFile).count())
                    .as("no leftover file, partial or otherwise").isZero();
        }
    }

    @Test
    void aKeyCannotClimbOutOfTheStorageRoot() {
        String[] attempts = {
                "../../etc/passwd",
                "h1/../../etc/passwd",
                "h1/p1/../../../secrets.pdf",
                "/etc/passwd",
                "h1/p1/..%2Fescape.pdf",
                "C:/windows/system32/config",
                "h1/p1/file with space.pdf",
                "h1/p1"};
        for (String attempt : attempts) {
            assertThatThrownBy(() -> storage.load(attempt))
                    .as("must refuse: %s", attempt)
                    .isInstanceOf(IllegalArgumentException.class);
        }
    }

    @Test
    void aBackslashKeyIsRefused() {
        String windowsStyle = "h1" + ((char) 92) + "p1" + ((char) 92) + "escape.pdf";
        assertThatThrownBy(() -> storage.load(windowsStyle))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void aNullOrEmptyKeyIsRefused() {
        assertThatThrownBy(() -> storage.load(null)).isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> storage.load("  ")).isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void everyResolvedPathStaysUnderTheRoot() throws Exception {
        var stored = storage.store("h1", "p1", "png", bytes("img"), 3);
        Path resolved = storage.resolveWithin(stored.storageKey());
        assertThat(resolved.normalize().startsWith(root.toRealPath())).isTrue();
    }

    /** A real file outside the root stays unreachable however the key is shaped. */
    @Test
    void aFileOutsideTheRootCannotBeReached() throws Exception {
        Path outside = root.getParent().resolve("outside-secret.pdf");
        Files.writeString(outside, "not yours");

        for (String attempt : new String[]{"../outside-secret.pdf", "h1/../../outside-secret.pdf"}) {
            assertThatThrownBy(() -> storage.load(attempt)).isInstanceOf(IllegalArgumentException.class);
        }
        assertThat(Files.readString(outside)).isEqualTo("not yours");
    }

    @Test
    void aMissingFileFailsWithoutNamingTheFilesystem() {
        var stored = storage.store("h1", "p1", "pdf", bytes("x"), 1);
        storage.deleteQuietly(stored.storageKey());

        assertThatThrownBy(() -> storage.load(stored.storageKey()))
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class)
                .satisfies(e -> assertThat(e.getMessage())
                        .as("an API client sees this")
                        .doesNotContain(root.toString()));
    }

    @Test
    void deletingSomethingAlreadyGoneIsQuiet() {
        assertThatCode(() -> storage.deleteQuietly("h1/p1/" + java.util.UUID.randomUUID() + ".pdf"))
                .doesNotThrowAnyException();
    }

    // -- symlink escape ----------------------------------------------------------

    /**
     * The escape lexical containment cannot see.
     *
     * <p>normalize() reasons about the text of a path. A directory inside the root that is a
     * symbolic link makes a perfectly well-formed key resolve somewhere else entirely, and the
     * old check called that contained because the spelling never left the root.
     */
    @Test
    void aSymlinkedDirectoryInsideTheRootIsNotAWayOut() throws Exception {
        Path external = Files.createDirectory(root.getParent().resolve("external-" + System.nanoTime()));
        Files.writeString(external.resolve("stolen.pdf"), "another tenant's report");
        Files.createSymbolicLink(root.resolve("h42"), external);

        String key = "h42/p1/" + java.util.UUID.randomUUID() + ".pdf";
        assertThatThrownBy(() -> storage.load(key))
                .as("reading through a planted link").isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> storage.store("h42", "p1", "pdf", bytes("x"), 1))
                .as("writing through a planted link")
                .isInstanceOfAny(IllegalArgumentException.class,
                        LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);
        assertThatCode(() -> storage.deleteQuietly(key)).doesNotThrowAnyException();

        assertThat(Files.readString(external.resolve("stolen.pdf")))
                .as("nothing outside the root was touched").isEqualTo("another tenant's report");
        assertThat(storage.exists(key)).isFalse();
    }

    /** The same, one level deeper: the patient directory is the link. */
    @Test
    void aSymlinkedPatientDirectoryIsNotAWayOut() throws Exception {
        Path external = Files.createDirectory(root.getParent().resolve("ext2-" + System.nanoTime()));
        Files.createDirectories(root.resolve("h7"));
        Files.createSymbolicLink(root.resolve("h7").resolve("p9"), external);

        assertThatThrownBy(() -> storage.store("h7", "p9", "pdf", bytes("x"), 1))
                .isInstanceOfAny(IllegalArgumentException.class,
                        LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);
        try (var walk = Files.walk(external)) {
            assertThat(walk.filter(Files::isRegularFile).count()).isZero();
        }
    }

    /** A link where the file itself should be must not be readable as that file. */
    @Test
    void aSymlinkedFileIsNotReadableAsADocument() throws Exception {
        Path secret = root.getParent().resolve("secret-" + System.nanoTime() + ".pdf");
        Files.writeString(secret, "not yours");

        Path dir = Files.createDirectories(root.resolve("h1").resolve("p1"));
        String name = java.util.UUID.randomUUID() + ".pdf";
        Files.createSymbolicLink(dir.resolve(name), secret);

        String key = "h1/p1/" + name;
        assertThat(storage.exists(key)).as("a link is not a document").isFalse();
        assertThatThrownBy(() -> storage.load(key))
                .as("refused while resolving, before anything is opened")
                .isInstanceOfAny(IllegalArgumentException.class,
                        LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);
        assertThat(Files.readString(secret)).isEqualTo("not yours");
    }

    /**
     * The race the checks could not see: the parent does not exist when the key is validated,
     * and is a symlink by the time the directory is created.
     *
     * <p>The seam fires exactly where an attacker would have to win -- between validation and the
     * open -- so this is deterministic rather than a hopeful loop. Storage must refuse, and the
     * directory the link points at must be untouched afterwards.
     */
    @Test
    void aParentDirectoryReplacedByASymlinkAfterValidationIsRefused() throws Exception {
        Path external = Files.createDirectory(root.getParent().resolve("race-" + System.nanoTime()));
        Files.writeString(external.resolve("existing.pdf"), "another tenant's report");

        var racing = new LocalVpsClinicalDocumentStorage(root.toString(), new MockEnvironment()) {
            @Override void beforeDirectoryOpen(String name) {
                // Plant the link the instant before the hospital directory is opened or created.
                Path parent = root.resolve(name);
                if ("h42".equals(name) && !Files.exists(parent, java.nio.file.LinkOption.NOFOLLOW_LINKS)) {
                    try {
                        Files.createSymbolicLink(parent, external);
                    } catch (java.io.IOException e) {
                        throw new IllegalStateException(e);
                    }
                }
            }
        };
        racing.initialise();

        assertThatThrownBy(() -> racing.store("h42", "p1", "pdf", bytes("stolen bytes"), 12))
                .as("the write must not go through the planted link")
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);

        try (var walk = Files.walk(external)) {
            assertThat(walk.filter(Files::isRegularFile).map(Path::getFileName).map(Path::toString))
                    .as("nothing was written outside the root")
                    .containsExactly("existing.pdf");
        }
        assertThat(Files.readString(external.resolve("existing.pdf"))).isEqualTo("another tenant's report");
    }

    /** The same race one level deeper, where only the patient directory is swapped. */
    @Test
    void aPatientDirectoryReplacedByASymlinkAfterValidationIsRefused() throws Exception {
        Path external = Files.createDirectory(root.getParent().resolve("race2-" + System.nanoTime()));

        var racing = new LocalVpsClinicalDocumentStorage(root.toString(), new MockEnvironment()) {
            @Override void beforeDirectoryOpen(String name) {
                Path parent = root.resolve("h7").resolve(name);
                if ("p9".equals(name) && Files.isDirectory(root.resolve("h7"))
                        && !Files.exists(parent, java.nio.file.LinkOption.NOFOLLOW_LINKS)) {
                    try {
                        Files.createSymbolicLink(parent, external);
                    } catch (java.io.IOException e) {
                        throw new IllegalStateException(e);
                    }
                }
            }
        };
        racing.initialise();

        assertThatThrownBy(() -> racing.store("h7", "p9", "pdf", bytes("stolen bytes"), 12))
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);

        try (var walk = Files.walk(external)) {
            assertThat(walk.filter(Files::isRegularFile).count()).isZero();
        }
    }

    // -- no-overwrite ------------------------------------------------------------

    /**
     * An entry that appears under the final name after everything has been validated.
     *
     * <p>The seam fires immediately before the document is created, which is the only moment
     * where a check-then-write implementation could be beaten. The stored bytes must not be
     * replaced and the upload must fail.
     */
    @Test
    void anEntryThatAppearsUnderTheFinalNameIsNeverOverwritten() throws Exception {
        var racing = new LocalVpsClinicalDocumentStorage(root.toString(), new MockEnvironment()) {
            @Override void beforeDocumentCreate(String storageKey) {
                try {
                    Files.writeString(root.resolve(storageKey), "another patient's report");
                } catch (java.io.IOException e) {
                    throw new IllegalStateException(e);
                }
            }
        };
        racing.initialise();

        assertThatThrownBy(() -> racing.store("h1", "p1", "pdf", bytes("incoming bytes"), 14))
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);

        try (var walk = Files.walk(root.resolve("h1").resolve("p1"))) {
            assertThat(walk.filter(Files::isRegularFile).map(f -> {
                try { return Files.readString(f); } catch (java.io.IOException e) { throw new IllegalStateException(e); }
            })).as("the entry that was already there is untouched, and nothing else was left")
               .containsExactly("another patient's report");
        }
    }

    /**
     * A symlink where the final name should be is not a document to overwrite either: the create
     * refuses it, and whatever it pointed at keeps its contents.
     */
    @Test
    void aSymlinkAppearingUnderTheFinalNameIsNotWrittenThrough() throws Exception {
        Path secret = root.getParent().resolve("target-" + System.nanoTime() + ".pdf");
        Files.writeString(secret, "not yours");

        var racing = new LocalVpsClinicalDocumentStorage(root.toString(), new MockEnvironment()) {
            @Override void beforeDocumentCreate(String storageKey) {
                try {
                    Files.createSymbolicLink(root.resolve(storageKey), secret);
                } catch (java.io.IOException e) {
                    throw new IllegalStateException(e);
                }
            }
        };
        racing.initialise();

        assertThatThrownBy(() -> racing.store("h1", "p1", "pdf", bytes("incoming bytes"), 14))
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);
        assertThat(Files.readString(secret)).isEqualTo("not yours");
    }

    /**
     * Permissions are set by the create, never by a second call on a name.
     *
     * <p>The staging directory is replaced with a link to somewhere outside the root at the one
     * moment a chmod could have followed it. The external directory must keep the permissions it
     * had, and nothing may be written into it.
     */
    @Test
    void aStagingDirectoryReplacedByASymlinkCannotChangeAnExternalTarget() throws Exception {
        Path external = Files.createDirectory(root.getParent().resolve("perm-" + System.nanoTime()));
        Files.writeString(external.resolve("kept.pdf"), "another tenant's report");
        var before = Files.getPosixFilePermissions(external);

        var racing = new LocalVpsClinicalDocumentStorage(root.toString(), new MockEnvironment()) {
            @Override void afterStagingCreate(Path staging) {
                try {
                    Files.delete(staging);
                    Files.createSymbolicLink(staging, external);
                } catch (java.io.IOException e) {
                    throw new IllegalStateException(e);
                }
            }
        };
        racing.initialise();

        assertThatThrownBy(() -> racing.store("h9", "p9", "pdf", bytes("stolen bytes"), 12))
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);

        assertThat(Files.getPosixFilePermissions(external))
                .as("no permission change reached the link's target").isEqualTo(before);
        try (var walk = Files.walk(external)) {
            assertThat(walk.filter(Files::isRegularFile).count())
                    .as("and nothing was written through it").isEqualTo(1);
        }
        assertThat(Files.readString(external.resolve("kept.pdf"))).isEqualTo("another tenant's report");
    }

    /** A directory this class creates is owner-only from the moment it exists. */
    @Test
    void createdDirectoriesAndDocumentsAreOwnerOnly() throws Exception {
        var stored = storage.store("h1", "p1", "pdf", bytes("x"), 1);

        assertThat(Files.getPosixFilePermissions(root.resolve("h1")))
                .containsExactlyInAnyOrder(java.nio.file.attribute.PosixFilePermission.OWNER_READ,
                        java.nio.file.attribute.PosixFilePermission.OWNER_WRITE,
                        java.nio.file.attribute.PosixFilePermission.OWNER_EXECUTE);
        assertThat(Files.getPosixFilePermissions(root.resolve(stored.storageKey())))
                .containsExactlyInAnyOrder(java.nio.file.attribute.PosixFilePermission.OWNER_READ,
                        java.nio.file.attribute.PosixFilePermission.OWNER_WRITE);
    }

    /** A configured root that is itself a link would make every check meaningless. */
    @Test
    void aSymlinkedStorageRootIsRefusedAtStartup() throws Exception {
        Path real = Files.createDirectory(root.resolve("real-store"));
        Path link = root.resolve("linked-store");
        Files.createSymbolicLink(link, real);

        var viaLink = new LocalVpsClinicalDocumentStorage(link.toString(), new MockEnvironment());
        assertThatThrownBy(viaLink::initialise)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("symbolic link");
    }

    /** Production must never invent somewhere ephemeral to keep clinical records. */
    @Test
    void productionRefusesToStartWithoutAConfiguredDirectory() {
        MockEnvironment production = new MockEnvironment();
        production.setActiveProfiles("prod");
        var unconfigured = new LocalVpsClinicalDocumentStorage("", production);

        assertThatThrownBy(unconfigured::initialise)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("HMS_DOCUMENT_STORAGE_PATH");
    }

    @Test
    void developmentFallsBackToATemporaryDirectory() {
        var dev = new LocalVpsClinicalDocumentStorage("", new MockEnvironment());
        assertThatCode(dev::initialise).doesNotThrowAnyException();
    }
}
