package com.hms.service.storage;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.mock.env.MockEnvironment;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * The storage layer, and the one thing it must never do: let a key point outside its own root.
 *
 * <p>Keys are generated by this class, so a key shaped like a path did not come from here. These
 * tests use a temporary directory -- nothing depends on a real server, a deployment path, or
 * anything existing on the machine running them.
 */
class LocalVpsClinicalDocumentStorageTest {

    @TempDir Path root;
    private LocalVpsClinicalDocumentStorage storage;

    @BeforeEach
    void setUp() {
        storage = new LocalVpsClinicalDocumentStorage(root.toString(), new MockEnvironment());
        storage.initialise();
    }

    private static InputStream bytes(String content) {
        return new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8));
    }

    @Test
    void aStoredDocumentCanBeReadBack() throws Exception {
        var stored = storage.store("h1", "p1", "pdf", bytes("report contents"), 15);

        assertThat(storage.exists(stored.storageKey())).isTrue();
        try (InputStream in = storage.load(stored.storageKey())) {
            assertThat(new String(in.readAllBytes(), StandardCharsets.UTF_8)).isEqualTo("report contents");
        }
        assertThat(stored.sizeBytes()).isEqualTo(15);
    }

    @Test
    void theKeyRevealsNothingAboutThePatient() {
        var stored = storage.store("h1", "p1", "pdf", bytes("x"), 1);

        assertThat(stored.storageKey())
                .as("no patient name, no original filename, nothing guessable")
                .doesNotContain("blood").doesNotContain("report").doesNotContain("Asha")
                .matches("h1/p1/[0-9a-f-]{36}[.]pdf");
    }

    @Test
    void twoUploadsOfTheSameFileDoNotCollide() {
        var first = storage.store("h1", "p1", "pdf", bytes("same"), 4);
        var second = storage.store("h1", "p1", "pdf", bytes("same"), 4);
        assertThat(first.storageKey()).isNotEqualTo(second.storageKey());
        assertThat(storage.exists(first.storageKey())).isTrue();
        assertThat(storage.exists(second.storageKey())).isTrue();
    }

    /** A half-written upload must never be left behind looking like a document. */
    @Test
    void nothingPartialSurvivesAFailedWrite() throws Exception {
        InputStream exploding = new InputStream() {
            @Override public int read() throws java.io.IOException {
                throw new java.io.IOException("connection dropped");
            }
        };

        assertThatThrownBy(() -> storage.store("h1", "p1", "pdf", exploding, 10))
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class);

        try (var walk = Files.walk(root)) {
            assertThat(walk.filter(Files::isRegularFile).count())
                    .as("no leftover file, partial or otherwise").isZero();
        }
    }

    @Test
    void aKeyCannotClimbOutOfTheStorageRoot() {
        String[] attempts = {
                "../../etc/passwd",
                "h1/../../etc/passwd",
                "h1/p1/../../../secrets.pdf",
                "/etc/passwd",
                "h1/p1/..%2Fescape.pdf",
                "C:/windows/system32/config",
                "h1/p1/file with space.pdf",
                "h1/p1"};
        for (String attempt : attempts) {
            assertThatThrownBy(() -> storage.load(attempt))
                    .as("must refuse: %s", attempt)
                    .isInstanceOf(IllegalArgumentException.class);
        }
    }

    @Test
    void aBackslashKeyIsRefused() {
        String windowsStyle = "h1" + ((char) 92) + "p1" + ((char) 92) + "escape.pdf";
        assertThatThrownBy(() -> storage.load(windowsStyle))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void aNullOrEmptyKeyIsRefused() {
        assertThatThrownBy(() -> storage.load(null)).isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> storage.load("  ")).isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void everyResolvedPathStaysUnderTheRoot() {
        var stored = storage.store("h1", "p1", "png", bytes("img"), 3);
        Path resolved = storage.resolveWithin(stored.storageKey());
        assertThat(resolved.normalize().startsWith(root.toAbsolutePath().normalize())).isTrue();
    }

    /** A real file outside the root stays unreachable however the key is shaped. */
    @Test
    void aFileOutsideTheRootCannotBeReached() throws Exception {
        Path outside = root.getParent().resolve("outside-secret.pdf");
        Files.writeString(outside, "not yours");

        for (String attempt : new String[]{"../outside-secret.pdf", "h1/../../outside-secret.pdf"}) {
            assertThatThrownBy(() -> storage.load(attempt)).isInstanceOf(IllegalArgumentException.class);
        }
        assertThat(Files.readString(outside)).isEqualTo("not yours");
    }

    @Test
    void aMissingFileFailsWithoutNamingTheFilesystem() {
        var stored = storage.store("h1", "p1", "pdf", bytes("x"), 1);
        storage.deleteQuietly(stored.storageKey());

        assertThatThrownBy(() -> storage.load(stored.storageKey()))
                .isInstanceOf(LocalVpsClinicalDocumentStorage.ClinicalDocumentStorageException.class)
                .satisfies(e -> assertThat(e.getMessage())
                        .as("an API client sees this")
                        .doesNotContain(root.toString()));
    }

    @Test
    void deletingSomethingAlreadyGoneIsQuiet() {
        assertThatCode(() -> storage.deleteQuietly("h1/p1/" + java.util.UUID.randomUUID() + ".pdf"))
                .doesNotThrowAnyException();
    }

    /** Production must never invent somewhere ephemeral to keep clinical records. */
    @Test
    void productionRefusesToStartWithoutAConfiguredDirectory() {
        MockEnvironment production = new MockEnvironment();
        production.setActiveProfiles("prod");
        var unconfigured = new LocalVpsClinicalDocumentStorage("", production);

        assertThatThrownBy(unconfigured::initialise)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("HMS_DOCUMENT_STORAGE_PATH");
    }

    @Test
    void developmentFallsBackToATemporaryDirectory() {
        var dev = new LocalVpsClinicalDocumentStorage("", new MockEnvironment());
        assertThatCode(dev::initialise).doesNotThrowAnyException();
    }
}
