-- Fresh-schema bootstrap for the HMS database.
--
-- Deliberately does NOT create or select a database. This file began life as a dump of one
-- particular deployment and carried that deployment's name in a CREATE DATABASE/USE pair, so
-- loading it anywhere else silently built the schema in the wrong place — the caller would see
-- "success" and an empty target. The database is the caller's decision:
--
--   mysql -u <user> -p <your_database> < setup/schema-full.sql
--
-- MySQL dump 10.13  Distrib 8.0.36, for Win64 (x86_64)
--
-- Originally generated by mysqldump; the source host and database name have been
-- removed because this file is no longer tied to either.
-- ------------------------------------------------------
-- Server version	9.4.0

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `appointments`
--

DROP TABLE IF EXISTS `appointments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `appointments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `appointment_date` date NOT NULL,
  `appointment_time` time(6) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `custom_id` varchar(255) DEFAULT NULL,
  `doctor_id` bigint NOT NULL,
  `hospital_id` bigint NOT NULL,
  `is_active` bit(1) NOT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `patient_id` bigint NOT NULL,
  `public_id` varchar(255) NOT NULL,
  `status` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_by8ybe23gqrq9m7r9knbgsilm` (`public_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `audit_logs`
--

DROP TABLE IF EXISTS `audit_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `audit_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action` varchar(255) NOT NULL,
  `details` varchar(1000) NOT NULL,
  `entity_id` varchar(255) DEFAULT NULL,
  `entity_type` varchar(255) DEFAULT NULL,
  `hospital_id` bigint DEFAULT NULL,
  `performed_by` varchar(255) NOT NULL,
  `public_id` varchar(255) NOT NULL,
  `reason` varchar(2000) DEFAULT NULL,
  `timestamp` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_cw6h8py7jx6jf1d4j3mjkrg47` (`public_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `beds`
--

DROP TABLE IF EXISTS `beds`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `beds` (
  `bed_id` bigint NOT NULL AUTO_INCREMENT,
  `bed_code` varchar(255) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `current_ipd_admission_id` bigint DEFAULT NULL,
  `hospital_id` bigint NOT NULL,
  `status` varchar(255) NOT NULL,
  `ward_id` bigint NOT NULL,
  PRIMARY KEY (`bed_id`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `billing`
--

DROP TABLE IF EXISTS `billing`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `billing` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` decimal(10,2) NOT NULL,
  `appointment_id` bigint DEFAULT NULL,
  `billing_type` varchar(255) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `custom_id` varchar(255) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `doctor_id` bigint NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint DEFAULT NULL,
  `opd_id` bigint DEFAULT NULL,
  `patient_id` bigint NOT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `payment_reference` varchar(100) DEFAULT NULL,
  `marked_paid_by` varchar(100) DEFAULT NULL,
  `payment_status` varchar(20) NOT NULL,
  `public_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_873yunoi4d9gm43g5bu8ltm9k` (`public_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `billing_items`
--

DROP TABLE IF EXISTS `billing_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `billing_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` decimal(10,2) NOT NULL,
  `billing_id` bigint NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `description` varchar(200) NOT NULL,
  `hospital_id` bigint NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `billing_payments`
--

DROP TABLE IF EXISTS `billing_payments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `billing_payments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` decimal(10,2) NOT NULL,
  `billing_id` bigint NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `mode` varchar(50) DEFAULT NULL,
  `reference` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `discharge_summary`
--

DROP TABLE IF EXISTS `discharge_summary`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `discharge_summary` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `discharge_notes` text,
  `final_diagnosis` text,
  `follow_up_date` date DEFAULT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `treatment_given` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_5poa40gpt44a152gibdlfe6sb` (`ipd_admission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `doctors`
--

DROP TABLE IF EXISTS `doctors`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `doctors` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `custom_id` varchar(255) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `is_active` bit(1) NOT NULL,
  `name` varchar(100) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `public_id` varchar(255) NOT NULL,
  `specialization` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_lqd2m2kx16cc3locfwtq02bek` (`public_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hospital_modules`
--

DROP TABLE IF EXISTS `hospital_modules`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `hospital_modules` (
  `hospital_id` bigint NOT NULL,
  `module_name` varchar(255) DEFAULT NULL,
  KEY `FKcn73q131q80psfovorxk09c13` (`hospital_id`),
  CONSTRAINT `FKcn73q131q80psfovorxk09c13` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hospitals`
--

DROP TABLE IF EXISTS `hospitals`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `hospitals` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `address` varchar(500) DEFAULT NULL,
  `case_paper_fee` decimal(10,2) DEFAULT NULL,
  `consultation_fee` decimal(10,2) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `custom_id` varchar(255) DEFAULT NULL,
  `is_active` bit(1) NOT NULL,
  `logo_url` varchar(500) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `opd_timings` varchar(100) DEFAULT NULL,
  `parent_organization` varchar(200) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `plan` varchar(20) DEFAULT NULL,
  `public_id` varchar(255) NOT NULL,
  `subscription_status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `type` varchar(20) NOT NULL DEFAULT 'HOSPITAL',
  `is_single_doctor` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_dre74r9dx5tme2mvsmu33ur77` (`public_id`),
  UNIQUE KEY `UK_snisvhrc8x0rcmph9cwiuqxvt` (`custom_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `inventory_transactions`
--

DROP TABLE IF EXISTS `inventory_transactions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `inventory_transactions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `branch_id` bigint DEFAULT NULL,
  `medicine_batch_id` bigint NOT NULL,
  `transaction_type` varchar(50) DEFAULT NULL,
  `quantity` decimal(38,2) NOT NULL,
  `quantity_before` decimal(38,2) DEFAULT NULL,
  `quantity_after` decimal(38,2) DEFAULT NULL,
  `reference_type` varchar(50) DEFAULT NULL,
  `reference_id` bigint DEFAULT NULL,
  `remarks` text,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `FKcmvc7jx2d37wg6116l0ghu3h7` (`medicine_batch_id`),
  CONSTRAINT `FKcmvc7jx2d37wg6116l0ghu3h7` FOREIGN KEY (`medicine_batch_id`) REFERENCES `medicine_batches` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `ipd_admission`
--

DROP TABLE IF EXISTS `ipd_admission`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `ipd_admission` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `admission_datetime` datetime(6) NOT NULL,
  `admission_type` varchar(255) NOT NULL,
  `bed_id` bigint NOT NULL,
  `discharge_datetime` datetime(6) DEFAULT NULL,
  `doctor_id` bigint NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_number` varchar(255) NOT NULL,
  `notes` text,
  `patient_id` bigint NOT NULL,
  `primary_diagnosis` text,
  `source_opd_id` bigint DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  `ward_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_3p2j5aiaxya8xnh9epblbmlhp` (`ipd_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lab_orders`
--

DROP TABLE IF EXISTS `lab_orders`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `lab_orders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `medical_record_id` bigint NOT NULL,
  `public_id` varchar(255) NOT NULL,
  `status` varchar(50) NOT NULL,
  `test_name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_9d9924cas2rwvtgkan0mtkmq` (`public_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `manufacturers`
--

DROP TABLE IF EXISTS `manufacturers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `manufacturers` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `address` text,
  `contact_person` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `hospital_id` bigint NOT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `license_number` varchar(255) DEFAULT NULL,
  `manufacturer_name` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `medical_records`
--

DROP TABLE IF EXISTS `medical_records`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `medical_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `appointment_id` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `diagnosis` varchar(1000) DEFAULT NULL,
  `doctor_id` bigint NOT NULL,
  `follow_up_date` date DEFAULT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint DEFAULT NULL,
  `opd_id` bigint DEFAULT NULL,
  `patient_id` bigint NOT NULL,
  `public_id` varchar(255) NOT NULL,
  `administered_items_json` varchar(3000) DEFAULT NULL,
  `symptoms` varchar(1000) DEFAULT NULL,
  `treatment_notes` varchar(2000) DEFAULT NULL,
  `visit_type` varchar(255) NOT NULL,
  `follow_up_instructions` varchar(1000) DEFAULT NULL,
  `follow_up_status` varchar(20) DEFAULT NULL,
  `actioned_opd_id` bigint DEFAULT NULL,
  `actioned_by_user_id` bigint DEFAULT NULL,
  `actioned_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_4elkgkxl6vd0j1p95r174acix` (`public_id`),
  UNIQUE KEY `UK_2nyonrbplqq716buy7u4ghmt8` (`appointment_id`),
  UNIQUE KEY `UK_8keap6v2c4lgf774c99jg4n7` (`opd_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `medicine_batches`
--

DROP TABLE IF EXISTS `medicine_batches`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `medicine_batches` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `branch_id` bigint DEFAULT NULL,
  `medicine_id` bigint NOT NULL,
  `batch_number` varchar(100) NOT NULL,
  `expiry_date` date NOT NULL,
  `manufacturing_date` date DEFAULT NULL,
  `mrp` decimal(38,2) NOT NULL,
  `purchase_rate` decimal(38,2) NOT NULL,
  `selling_price` decimal(38,2) NOT NULL,
  `current_quantity` decimal(38,2) DEFAULT NULL,
  `reserved_quantity` decimal(38,2) DEFAULT NULL,
  `location_id` bigint DEFAULT NULL,
  `supplier_id` bigint DEFAULT NULL,
  `purchase_invoice_item_id` bigint DEFAULT NULL,
  `gst_percentage` decimal(38,2) DEFAULT NULL,
  `remarks` text,
  `status` varchar(30) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `FKs60kqtwcpr2qtqsd9xle3eqot` (`location_id`),
  KEY `FKchyofsp38cdkq2erdq4a9r1uc` (`medicine_id`),
  KEY `FKlds0umb8e6lk2afnbqnmjyy41` (`supplier_id`),
  CONSTRAINT `FKchyofsp38cdkq2erdq4a9r1uc` FOREIGN KEY (`medicine_id`) REFERENCES `medicine_master` (`id`),
  CONSTRAINT `FKlds0umb8e6lk2afnbqnmjyy41` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`),
  CONSTRAINT `FKs60kqtwcpr2qtqsd9xle3eqot` FOREIGN KEY (`location_id`) REFERENCES `storage_locations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `medicine_categories`
--

DROP TABLE IF EXISTS `medicine_categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `medicine_categories` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `category_name` varchar(255) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `description` text,
  `hospital_id` bigint NOT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `medicine_master`
--

DROP TABLE IF EXISTS `medicine_master`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `medicine_master` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `branch_id` bigint DEFAULT NULL,
  `medicine_code` varchar(50) DEFAULT NULL,
  `medicine_name` varchar(255) NOT NULL,
  `generic_name` varchar(255) DEFAULT NULL,
  `category_id` bigint DEFAULT NULL,
  `manufacturer_id` bigint DEFAULT NULL,
  `manufacturer_name` varchar(255) DEFAULT NULL,
  `medicine_type` varchar(50) DEFAULT NULL,
  `schedule_type` varchar(20) DEFAULT NULL,
  `dosage_form` varchar(100) DEFAULT NULL,
  `strength` varchar(100) DEFAULT NULL,
  `unit_of_measure` varchar(50) DEFAULT NULL,
  `reorder_level` int DEFAULT '0',
  `min_stock_level` int DEFAULT '0',
  `gst_percentage` decimal(38,2) DEFAULT NULL,
  `requires_prescription` tinyint(1) DEFAULT '1',
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `medicine_code` (`medicine_code`),
  KEY `FKqbtdqift3k79579mmsb1hp42d` (`category_id`),
  KEY `FK7t8h6ykhxexnd6q6w2etvg9u7` (`manufacturer_id`),
  CONSTRAINT `FK7t8h6ykhxexnd6q6w2etvg9u7` FOREIGN KEY (`manufacturer_id`) REFERENCES `manufacturers` (`id`),
  CONSTRAINT `FKqbtdqift3k79579mmsb1hp42d` FOREIGN KEY (`category_id`) REFERENCES `medicine_categories` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `medicines`
--

DROP TABLE IF EXISTS `medicines`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `medicines` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `default_dosage` varchar(255) DEFAULT NULL,
  `default_duration` varchar(255) DEFAULT NULL,
  `default_frequency` varchar(255) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `hospital_id` bigint DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `manufacturer` varchar(255) DEFAULT NULL,
  `min_stock_level` int DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `stock_quantity` int NOT NULL,
  `type` varchar(255) DEFAULT NULL,
  `unit_price` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `opd`
--

DROP TABLE IF EXISTS `opd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `opd` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `bp` varchar(255) DEFAULT NULL,
  `case_id` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `problem` text,
  `pulse` int DEFAULT NULL,
  `spo2` int DEFAULT NULL,
  `status` enum('QUEUED','CONSULTED','COMPLETED','IN_IPD') NOT NULL,
  `ipd_admit_recommended` tinyint(1) NOT NULL DEFAULT '0',
  `temperature` double DEFAULT NULL,
  `token_number` int DEFAULT NULL,
  `visit_type` enum('NEW','FOLLOWUP') DEFAULT NULL,
  `weight` double DEFAULT NULL,
  `height` double DEFAULT NULL,
  `custom_vitals` text,
  `doctor_id` bigint DEFAULT NULL,
  `patient_id` bigint DEFAULT NULL,
  `receptionist_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_1hooemtjkcvad3j015rxyddlm` (`case_id`),
  KEY `FKkrh8ux3vbkckqx3tslhqa4wok` (`doctor_id`),
  KEY `FKjmn16oyjgbruv844ufcyolbjd` (`patient_id`),
  KEY `FKjlnk1jk30lio8g8wckvbnjrf9` (`receptionist_id`),
  CONSTRAINT `FKjlnk1jk30lio8g8wckvbnjrf9` FOREIGN KEY (`receptionist_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKjmn16oyjgbruv844ufcyolbjd` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`),
  CONSTRAINT `FKkrh8ux3vbkckqx3tslhqa4wok` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `patients`
--

DROP TABLE IF EXISTS `patients`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `patients` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `address` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `custom_id` varchar(255) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `gender` varchar(10) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `is_active` bit(1) NOT NULL,
  `medical_history` varchar(1000) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `public_id` varchar(255) NOT NULL,
  `status` enum('REGISTERED','CONSULTING','COMPLETED') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_8isyrjl9ji56k5uv4cgp9p2q6` (`public_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `pharmacy_audit_logs`
--

DROP TABLE IF EXISTS `pharmacy_audit_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `pharmacy_audit_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `username` varchar(255) NOT NULL,
  `user_role` varchar(50) NOT NULL,
  `action_type` varchar(100) NOT NULL,
  `module` varchar(100) NOT NULL,
  `entity_name` varchar(255) DEFAULT NULL,
  `entity_id` bigint DEFAULT NULL,
  `old_value` text DEFAULT NULL,
  `new_value` text DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_pal_hospital_id` (`hospital_id`),
  KEY `idx_pal_action_type` (`action_type`),
  KEY `idx_pal_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `pharmacy_sale_items`
--

DROP TABLE IF EXISTS `pharmacy_sale_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `pharmacy_sale_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sale_id` bigint NOT NULL,
  `medicine_batch_id` bigint NOT NULL,
  `prescribed_quantity` decimal(10,2) DEFAULT NULL,
  `sold_quantity` decimal(10,2) DEFAULT NULL,
  `returned_quantity` decimal(10,2) NOT NULL DEFAULT '0.00',
  `unit_price` decimal(10,2) DEFAULT NULL,
  `discount_percentage` decimal(5,2) DEFAULT NULL,
  `gst_percentage` decimal(5,2) DEFAULT NULL,
  `line_total` decimal(12,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `pharmacy_sales`
--

DROP TABLE IF EXISTS `pharmacy_sales`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `pharmacy_sales` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `branch_id` bigint DEFAULT NULL,
  `invoice_number` varchar(100) DEFAULT NULL,
  `patient_id` bigint DEFAULT NULL,
  `prescription_id` bigint DEFAULT NULL,
  `doctor_id` bigint DEFAULT NULL,
  `pharmacist_id` bigint DEFAULT NULL,
  `sale_type` varchar(30) DEFAULT NULL,
  `subtotal` decimal(12,2) DEFAULT NULL,
  `discount_amount` decimal(12,2) DEFAULT NULL,
  `gst_amount` decimal(12,2) DEFAULT NULL,
  `total_amount` decimal(12,2) DEFAULT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `payment_status` varchar(50) DEFAULT NULL,
  `posting_status` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_number` (`invoice_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `prescriptions`
--

DROP TABLE IF EXISTS `prescriptions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
DROP TABLE IF EXISTS `opd_idempotency`;
CREATE TABLE `opd_idempotency` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `idempotency_key` varchar(100) NOT NULL,
  `opd_id` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_opd_idempotency` (`hospital_id`,`idempotency_key`),
  KEY `idx_opd_idempotency_opd` (`opd_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `prescriptions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `dosage` varchar(50) DEFAULT NULL,
  `duration` varchar(50) DEFAULT NULL,
  `duration_days` int DEFAULT NULL,
  `frequency` varchar(50) DEFAULT NULL,
  `hospital_id` bigint NOT NULL,
  `instructions` varchar(200) DEFAULT NULL,
  `food_timing` varchar(20) DEFAULT NULL,
  `medical_record_id` bigint NOT NULL,
  `medicine_name` varchar(255) NOT NULL,
  `route` varchar(255) NOT NULL,
  `start_date` date DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `purchase_invoice_items`
--

DROP TABLE IF EXISTS `purchase_invoice_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `purchase_invoice_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `purchase_invoice_id` bigint NOT NULL,
  `medicine_id` bigint NOT NULL,
  `batch_number` varchar(100) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `quantity` decimal(38,2) DEFAULT NULL,
  `free_quantity` decimal(38,2) DEFAULT NULL,
  `purchase_rate` decimal(38,2) DEFAULT NULL,
  `mrp` decimal(38,2) DEFAULT NULL,
  `selling_price` decimal(38,2) DEFAULT NULL,
  `gst_percentage` decimal(38,2) DEFAULT NULL,
  `line_total` decimal(38,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKg67d6qh5bq0jm6cnjogocjfy0` (`medicine_id`),
  CONSTRAINT `FKg67d6qh5bq0jm6cnjogocjfy0` FOREIGN KEY (`medicine_id`) REFERENCES `medicine_master` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `purchase_invoices`
--

DROP TABLE IF EXISTS `purchase_invoices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `purchase_invoices` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `branch_id` bigint DEFAULT NULL,
  `supplier_id` bigint NOT NULL,
  `invoice_number` varchar(100) DEFAULT NULL,
  `invoice_date` date DEFAULT NULL,
  `subtotal` decimal(38,2) DEFAULT NULL,
  `discount_amount` decimal(38,2) DEFAULT NULL,
  `gst_amount` decimal(38,2) DEFAULT NULL,
  `total_amount` decimal(38,2) DEFAULT NULL,
  `payment_status` varchar(50) DEFAULT NULL,
  `posting_status` varchar(50) DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `FKa0fe6yai855h0xkk72fhmpk2a` (`supplier_id`),
  CONSTRAINT `FKa0fe6yai855h0xkk72fhmpk2a` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `queue_entry`
--

DROP TABLE IF EXISTS `queue_entry`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `queue_entry` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `token_number` int DEFAULT NULL,
  `doctor_id` bigint DEFAULT NULL,
  `opd_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKhym5nwrldoiu0p5bkexif1pbd` (`doctor_id`),
  KEY `FK46n948328s187drytewghqf70` (`opd_id`),
  CONSTRAINT `FK46n948328s187drytewghqf70` FOREIGN KEY (`opd_id`) REFERENCES `opd` (`id`),
  CONSTRAINT `FKhym5nwrldoiu0p5bkexif1pbd` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sale_returns`
--

DROP TABLE IF EXISTS `sale_returns`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `sale_returns` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `sale_id` bigint NOT NULL,
  `return_reason` text,
  `refund_amount` decimal(12,2) DEFAULT NULL,
  `approved_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `storage_locations`
--

DROP TABLE IF EXISTS `storage_locations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `storage_locations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `hospital_id` bigint NOT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `location_name` varchar(255) NOT NULL,
  `location_type` varchar(255) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `suppliers`
--

DROP TABLE IF EXISTS `suppliers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `suppliers` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `address` text,
  `contact_person` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `credit_days` int DEFAULT NULL,
  `drug_license_number` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `gst_number` varchar(255) DEFAULT NULL,
  `hospital_id` bigint NOT NULL,
  `branch_id` bigint DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `supplier_name` varchar(255) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `custom_id` varchar(255) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `hospital_id` bigint DEFAULT NULL,
  `branch_id` bigint DEFAULT NULL,
  `is_active` bit(1) NOT NULL,
  `name` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `public_id` varchar(255) NOT NULL,
  `role` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_6dotkott2kjsp8vw4d0m25fb7` (`email`),
  UNIQUE KEY `UK_s24bux761rbgowsl7a4b386ba` (`public_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `pharmacy_branch`
-- (Multi Pharmacy branches/outlets under one owner tenant)
--
DROP TABLE IF EXISTS `pharmacy_branch`;
CREATE TABLE `pharmacy_branch` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `name` varchar(255) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `login_user_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pharmacy_branch_hospital` (`hospital_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `wards`
--

DROP TABLE IF EXISTS `wards`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
--
-- Table structure for table `icu_stay`  (ICU Phase 3)
--
CREATE TABLE `icu_stay` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `ward_id` bigint NOT NULL,
  `status` varchar(10) NOT NULL DEFAULT 'ACTIVE',
  `source` varchar(20) NOT NULL,
  `source_ref_id` bigint DEFAULT NULL,
  `admitted_at` datetime(6) NOT NULL,
  `admission_reason` varchar(255) DEFAULT NULL,
  `intensivist_doctor_id` bigint DEFAULT NULL,
  `admitted_by_user_id` bigint DEFAULT NULL,
  `disposition` varchar(20) DEFAULT NULL,
  `discharged_at` datetime(6) DEFAULT NULL,
  `discharged_by_user_id` bigint DEFAULT NULL,
  `active_marker` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_stay_public_id` (`public_id`),
  UNIQUE KEY `uk_icu_stay_active` (`hospital_id`,`active_marker`),
  KEY `idx_icu_stay_admission` (`ipd_admission_id`),
  KEY `idx_icu_stay_hospital` (`hospital_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wards` (
  `ward_id` bigint NOT NULL AUTO_INCREMENT,
  `bed_price` decimal(38,2) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `floor_number` int DEFAULT NULL,
  `incharge_nurse_id` bigint DEFAULT NULL,
  `hospital_id` bigint NOT NULL,
  `total_beds` int NOT NULL,
  `ward_name` varchar(255) NOT NULL,
  `unit_type` varchar(20) NOT NULL DEFAULT 'GENERAL',
  PRIMARY KEY (`ward_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-05-13 16:27:45

-- Performance indexes: hospital_id scoping + frequently filtered columns.
--
-- These used IF NOT EXISTS, which MySQL 8 does not support on CREATE INDEX (it is accepted by
-- H2 and Postgres). The whole block therefore aborted on the first statement, which is why the
-- three genuinely broken entries below went unnoticed for so long — nothing ever reached them.
-- This file creates a schema from nothing, so the indexes cannot already exist and the guard
-- bought nothing even where it parsed.
CREATE INDEX idx_patients_hospital ON patients(hospital_id);
CREATE INDEX idx_appointments_hospital_date ON appointments(hospital_id, appointment_date);
CREATE INDEX idx_billing_hospital_status ON billing(hospital_id, payment_status);
CREATE INDEX idx_medicine_batches_expiry ON medicine_batches(hospital_id, expiry_date);
CREATE INDEX idx_audit_logs_hospital_ts ON audit_logs(hospital_id, timestamp);
CREATE INDEX idx_doctors_hospital ON doctors(hospital_id);
-- The table is `ipd_admission`, singular. The old line named `ipd_admissions` and would have
-- failed with "table doesn't exist" even once the syntax was valid.
CREATE INDEX idx_ipd_admission_hospital_status ON ipd_admission(hospital_id, status);
-- Follow-up due/overdue list: one facility across a date window (V17).
CREATE TABLE `patient_documents` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(64) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `opd_id` bigint DEFAULT NULL,
  `ipd_admission_id` bigint DEFAULT NULL,
  `document_type` varchar(40) NOT NULL,
  `title` varchar(200) NOT NULL,
  `report_date` date DEFAULT NULL,
  `source` varchar(200) DEFAULT NULL,
  `notes` varchar(1000) DEFAULT NULL,
  `original_file_name` varchar(255) NOT NULL,
  `mime_type` varchar(100) NOT NULL,
  `file_size_bytes` bigint NOT NULL,
  `storage_key` varchar(255) NOT NULL,
  `uploaded_by_user_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `archived_by_user_id` bigint DEFAULT NULL,
  `archived_at` datetime(6) DEFAULT NULL,
  `archive_reason` varchar(500) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_patient_documents_public_id` (`public_id`),
  KEY `idx_patient_documents_patient` (`hospital_id`,`patient_id`,`report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_medical_records_followup ON medical_records(hospital_id, follow_up_date);
-- One follow-up becomes at most one visit (V18). NULLs do not collide, so unactioned
-- follow-ups are unconstrained.
CREATE UNIQUE INDEX uk_medical_records_actioned_opd ON medical_records(actioned_opd_id);

-- Deliberately NOT indexed here:
--   opd(hospital_id, ...) — `opd` has no hospital_id column and never has. Its tenancy is
--     derived through patient_id/doctor_id, which is what OpdRepositoryScopingArchTest fences.
--   users(email) — already covered by the UNIQUE key on that column; a second index on the
--     same column costs writes and buys nothing.

--
-- Table structure for table `plans`
-- (Platform-level subscription plans for hospitals)
--

DROP TABLE IF EXISTS `plans`;
CREATE TABLE `plans` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `type` varchar(20) NOT NULL,
  `monthly_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `yearly_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `in_clinic` tinyint(1) NOT NULL DEFAULT 0,
  `multi_outlet` tinyint(1) NOT NULL DEFAULT 0,
  `max_outlets` int DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_plans_public_id` (`public_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `plan_modules`
-- (Element collection for Plan.modules)
--

DROP TABLE IF EXISTS `plan_modules`;
CREATE TABLE `plan_modules` (
  `plan_id` bigint NOT NULL,
  `module_name` varchar(255) DEFAULT NULL,
  KEY `FK_plan_modules_plan_id` (`plan_id`),
  CONSTRAINT `FK_plan_modules_plan_id` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `plan_features`
-- (Element collection for Plan.features)
--

DROP TABLE IF EXISTS `plan_features`;
CREATE TABLE `plan_features` (
  `plan_id` bigint NOT NULL,
  `feature_name` varchar(255) DEFAULT NULL,
  KEY `FK_plan_features_plan_id` (`plan_id`),
  CONSTRAINT `FK_plan_features_plan_id` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `hospital_plan_subscriptions`
-- (Tracks which plan each hospital is subscribed to)
--

DROP TABLE IF EXISTS `hospital_plan_subscriptions`;
CREATE TABLE `hospital_plan_subscriptions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `plan_id` bigint NOT NULL,
  `billing_period` varchar(20) NOT NULL,
  `assigned_at` datetime(6) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `assigned_by` bigint DEFAULT NULL,
  `is_current` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `FK_hps_hospital_id` (`hospital_id`),
  KEY `FK_hps_plan_id` (`plan_id`),
  CONSTRAINT `FK_hps_hospital_id` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`),
  CONSTRAINT `FK_hps_plan_id` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `hospital_settings`
-- (Per-hospital operational toggles: reception mode, billing handler, etc.)
--

DROP TABLE IF EXISTS `hospital_settings`;
CREATE TABLE `hospital_settings` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `reception_mode` varchar(20) NOT NULL DEFAULT 'HAS_RECEPTIONIST',
  `billing_handler` varchar(20) NOT NULL DEFAULT 'RECEPTIONIST',
  `in_clinic` tinyint(1) NOT NULL DEFAULT 1,
  `barcode_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `separate_nurse_login` tinyint(1) NOT NULL DEFAULT 0,
  `ot_incharge_enabled` tinyint(1) NOT NULL DEFAULT 0,
  -- Print Settings: pages included in the consultation-complete combined print.
  `print_case_paper` tinyint(1) NOT NULL DEFAULT 1,
  `print_bill` tinyint(1) NOT NULL DEFAULT 1,
  `print_prescription` tinyint(1) NOT NULL DEFAULT 1,
  `print_in_clinic` tinyint(1) NOT NULL DEFAULT 1,
  -- FIRST = charge consultation + case-paper at OPD entry; LAST = current flow.
  `bill_payment_timing` varchar(10) NOT NULL DEFAULT 'LAST',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_hospital_settings_hospital_id` (`hospital_id`),
  CONSTRAINT `FK_hospital_settings_hospital_id` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Consultation note presets (per-hospital quick-note phrases doctors can
-- insert with one click into Treatment Notes)
--

CREATE TABLE `consultation_note_presets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `field_type` varchar(30) NOT NULL,
  `text` varchar(255) NOT NULL,
  `display_order` int NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_consultation_note_presets_hospital` (`hospital_id`),
  CONSTRAINT `FK_consultation_note_presets_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Prescription presets (per-hospital named bundles of medicines a doctor
-- can apply to a prescription in one action)
--

CREATE TABLE `prescription_presets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `name` varchar(150) NOT NULL,
  -- PRESCRIPTION (medicines a doctor prescribes) or IN_CLINIC (bundles of stock medicines
  -- administered in the clinic). Two preset lists sharing one table.
  `preset_type` varchar(20) NOT NULL DEFAULT 'PRESCRIPTION',
  `display_order` int NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_prescription_presets_hospital` (`hospital_id`),
  CONSTRAINT `FK_prescription_presets_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `prescription_preset_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `preset_id` bigint NOT NULL,
  `medicine_name` varchar(255) NOT NULL,
  `dosage` varchar(50) DEFAULT NULL,
  `frequency` varchar(50) DEFAULT NULL,
  `duration` varchar(50) DEFAULT NULL,
  `instructions` varchar(200) DEFAULT NULL,
  -- IN_CLINIC items only: the stock medicine + units to administer, so applying a preset
  -- still deducts from Medicine Inventory. NULL for PRESCRIPTION presets (free-text names).
  `medicine_id` bigint DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `sort_order` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_prescription_preset_items_preset` (`preset_id`),
  CONSTRAINT `FK_prescription_preset_items_preset` FOREIGN KEY (`preset_id`) REFERENCES `prescription_presets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Inventory items catalog (non-medicine hospital inventory: syringes,
-- fluids, consumables, surgical items, gloves, etc.). This table was
-- previously created only via Hibernate ddl-auto=update from the
-- InventoryItem entity and had never been added to this canonical dump;
-- documented here now, including has_own_stock added by
-- DatabaseMigrationRunner.ensureInventoryItemHasOwnStockColumn().
--

CREATE TABLE `inventory_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `type` varchar(50) DEFAULT NULL,
  `manufacturer` varchar(100) DEFAULT NULL,
  `hospital_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `linked_fee_id` bigint DEFAULT NULL,
  `relative_item_ids` varchar(1000) DEFAULT NULL,
  `has_own_stock` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_master_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `hospital_services` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `name` varchar(150) NOT NULL,
  `charge` decimal(10,2) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_hospital_services_hospital` (`hospital_id`),
  CONSTRAINT `FK_hospital_services_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `hospital_service_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `service_id` bigint NOT NULL,
  `master_item_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_hospital_service_items_service` (`service_id`),
  CONSTRAINT `FK_hospital_service_items_service` FOREIGN KEY (`service_id`) REFERENCES `hospital_services` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module (Phase 1): thin staff profile for NURSE users (HOSPITAL tenant only).
CREATE TABLE `nurse_profiles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `custom_id` varchar(255) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `hospital_id` bigint NOT NULL,
  `name` varchar(100) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `license_number` varchar(50) DEFAULT NULL,
  `ward_id` bigint DEFAULT NULL,
  `is_incharge` tinyint(1) NOT NULL DEFAULT 0,
  `gender` varchar(10) DEFAULT NULL,
  `qualification` varchar(120) DEFAULT NULL,
  `registration_number` varchar(60) DEFAULT NULL,
  `joining_date` date DEFAULT NULL,
  `on_shift` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_nurse_profiles_public_id` (`public_id`),
  KEY `idx_nurse_profiles_hospital` (`hospital_id`),
  KEY `idx_nurse_profiles_user` (`user_id`),
  CONSTRAINT `FK_nurse_profiles_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module (Phase 1): manual assignment of a nurse to an IPD admission.
CREATE TABLE `patient_nurse_assignments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `nurse_user_id` bigint NOT NULL,
  `assigned_by_user_id` bigint NOT NULL,
  `assigned_at` datetime(6) NOT NULL,
  `unassigned_at` datetime(6) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_pna_public_id` (`public_id`),
  KEY `idx_pna_admission_active` (`ipd_admission_id`,`is_active`),
  KEY `idx_pna_nurse_active` (`nurse_user_id`,`is_active`),
  KEY `idx_pna_hospital_active` (`hospital_id`,`is_active`),
  CONSTRAINT `FK_pna_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ICU (Phase 9): alert thresholds. Ships EMPTY - no row means no alert, because a default
-- threshold would be the system deciding what a normal value is. No alert-event table by
-- decision: this phase stores thresholds only.
CREATE TABLE `icu_alert_threshold` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `source` varchar(20) NOT NULL,
  `metric_key` varchar(60) NOT NULL,
  `min_value` decimal(12,3) DEFAULT NULL,
  `max_value` decimal(12,3) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `updated_by_user_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_alert_public_id` (`public_id`),
  UNIQUE KEY `uk_icu_alert_metric` (`hospital_id`,`source`,`metric_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ICU (Phase 8): severity scores, and the small setting saying which a hospital uses.
-- Components are a fixed Java registry (SeverityScoreRegistry), NOT a configurable catalogue:
-- a renamed SOFA component is no longer comparable to anyone else's SOFA.
CREATE TABLE `icu_score_type_setting` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `score_type` varchar(20) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_score_type_public_id` (`public_id`),
  UNIQUE KEY `uk_icu_score_type` (`hospital_id`,`score_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `icu_severity_score` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `icu_stay_id` bigint DEFAULT NULL,
  `score_type` varchar(20) NOT NULL,
  `components_json` text,
  `total_score` int DEFAULT NULL,
  `scored_at` datetime(6) NOT NULL,
  `recorded_by_user_id` bigint DEFAULT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `supersedes_score_id` bigint DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_score_public_id` (`public_id`),
  KEY `idx_icu_score_admission` (`ipd_admission_id`,`score_type`,`scored_at`),
  KEY `idx_icu_score_hospital` (`hospital_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ICU (Phase 7): the ventilator parameter catalogue (configuration) and the timed
-- snapshots that reference it by stable param_key (clinical record). Kept apart on purpose:
-- disabling or renaming a parameter must never rewrite a recorded value.
CREATE TABLE `icu_ventilator_parameter` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `param_key` varchar(60) NOT NULL,
  `display_name` varchar(60) NOT NULL,
  `unit` varchar(20) DEFAULT NULL,
  `category` varchar(20) NOT NULL DEFAULT 'SETTING',
  `value_type` varchar(20) NOT NULL DEFAULT 'NUMBER',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `is_custom` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` int DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_vent_param_public_id` (`public_id`),
  UNIQUE KEY `uk_icu_vent_param_key` (`hospital_id`,`param_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `icu_ventilator_setting` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `icu_stay_id` bigint DEFAULT NULL,
  `ventilation_status` varchar(20) NOT NULL,
  `values_json` text,
  `observed_at` datetime(6) NOT NULL,
  `recorded_by_user_id` bigint DEFAULT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `supersedes_setting_id` bigint DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_vent_public_id` (`public_id`),
  KEY `idx_icu_vent_admission` (`ipd_admission_id`,`observed_at`),
  KEY `idx_icu_vent_hospital` (`hospital_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ICU (Phase 6): continuous infusions and their append-only rate history.
CREATE TABLE `icu_infusion` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `prescription_id` bigint DEFAULT NULL,
  `medicine_name` varchar(255) NOT NULL,
  `started_at` datetime(6) NOT NULL,
  `stopped_at` datetime(6) DEFAULT NULL,
  `stop_reason` varchar(255) DEFAULT NULL,
  `started_by_user_id` bigint DEFAULT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_inf_public_id` (`public_id`),
  KEY `idx_icu_inf_admission` (`ipd_admission_id`),
  KEY `idx_icu_inf_hospital` (`hospital_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `icu_infusion_rate` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `icu_infusion_id` bigint NOT NULL,
  `rate_value` decimal(12,3) NOT NULL,
  `rate_unit` varchar(20) NOT NULL,
  `effective_from` datetime(6) NOT NULL,
  `recorded_by_user_id` bigint DEFAULT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `supersedes_rate_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_inf_rate_public_id` (`public_id`),
  KEY `idx_icu_inf_rate_infusion` (`icu_infusion_id`),
  KEY `idx_icu_inf_rate_effective` (`icu_infusion_id`,`effective_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module (Phase 1): time-series IPD vitals recorded by nurses.
CREATE TABLE `icu_io_entry` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `direction` varchar(6) NOT NULL,
  `route` varchar(30) NOT NULL,
  `volume_ml` int NOT NULL,
  `occurred_at` datetime(6) NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `recorded_by_user_id` bigint DEFAULT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `supersedes_io_entry_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_icu_io_public_id` (`public_id`),
  KEY `idx_icu_io_admission` (`ipd_admission_id`),
  KEY `idx_icu_io_hospital` (`hospital_id`),
  KEY `idx_icu_io_occurred` (`ipd_admission_id`,`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `vitals_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `recorded_by_user_id` bigint NOT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `recorded_at` datetime(6) NOT NULL,
  `temperature` decimal(12,1) DEFAULT NULL,
  `pulse` int DEFAULT NULL,
  `bp_systolic` int DEFAULT NULL,
  `bp_diastolic` int DEFAULT NULL,
  `respiratory_rate` int DEFAULT NULL,
  `spo2` int DEFAULT NULL,
  `weight` decimal(12,2) DEFAULT NULL,
  `pain_score` int DEFAULT NULL,
  `remarks` varchar(500) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `map_mmhg` int DEFAULT NULL,
  `cvp_cmh2o` int DEFAULT NULL,
  `urine_output_ml` int DEFAULT NULL,
  `gcs_eye` int DEFAULT NULL,
  `gcs_verbal` int DEFAULT NULL,
  `gcs_motor` int DEFAULT NULL,
  `gcs_total` int DEFAULT NULL,
  `supersedes_vitals_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_vitals_public_id` (`public_id`),
  KEY `idx_vitals_admission_time` (`ipd_admission_id`,`recorded_at`),
  KEY `idx_vitals_hospital` (`hospital_id`),
  CONSTRAINT `FK_vitals_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module (Phase 1): nursing observation notes.
CREATE TABLE `nursing_notes` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `nurse_user_id` bigint NOT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `note_text` text NOT NULL,
  `orders` text,
  `category` varchar(40) DEFAULT NULL,
  `surgery_id` bigint DEFAULT NULL,
  `recorded_at` datetime(6) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_nursing_notes_public_id` (`public_id`),
  KEY `idx_nursing_notes_admission_time` (`ipd_admission_id`,`recorded_at`),
  KEY `idx_nursing_notes_hospital` (`hospital_id`),
  CONSTRAINT `FK_nursing_notes_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module (Phase 1): medication administration records (against doctor's ACTIVE prescriptions).
CREATE TABLE `medication_administrations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `prescription_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `nurse_user_id` bigint NOT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `scheduled_time` datetime(6) DEFAULT NULL,
  `administered_time` datetime(6) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `remarks` varchar(500) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_mar_public_id` (`public_id`),
  KEY `idx_mar_admission_time` (`ipd_admission_id`,`administered_time`),
  KEY `idx_mar_prescription` (`prescription_id`),
  KEY `idx_mar_hospital` (`hospital_id`),
  CONSTRAINT `FK_mar_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module (Phase 1, M7): manual tasks.
CREATE TABLE `manual_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `title` varchar(150) NOT NULL,
  `description` text DEFAULT NULL,
  `assigned_to_nurse_user_id` bigint NOT NULL,
  `assigned_by_user_id` bigint NOT NULL,
  `ipd_admission_id` bigint DEFAULT NULL,
  `priority` varchar(10) NOT NULL DEFAULT 'MEDIUM',
  `status` varchar(15) NOT NULL DEFAULT 'PENDING',
  `due_date` datetime(6) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `operative_note` text,
  `operative_note_by_user_id` bigint DEFAULT NULL,
  `operative_note_at` datetime(6) DEFAULT NULL,
  `completion_remarks` varchar(500) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_manual_tasks_public_id` (`public_id`),
  KEY `idx_tasks_nurse_status` (`assigned_to_nurse_user_id`,`status`),
  KEY `idx_tasks_hospital_status` (`hospital_id`,`status`),
  KEY `idx_tasks_admission` (`ipd_admission_id`),
  CONSTRAINT `FK_tasks_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module (Phase 1, M8): notifications.
CREATE TABLE `notifications` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `recipient_user_id` bigint NOT NULL,
  `type` varchar(30) NOT NULL,
  `title` varchar(150) NOT NULL,
  `message` text NOT NULL,
  `reference_type` varchar(50) DEFAULT NULL,
  `reference_id` bigint DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT '0',
  `read_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_notifications_public_id` (`public_id`),
  KEY `idx_ntf_recipient` (`recipient_user_id`),
  KEY `idx_ntf_hospital` (`hospital_id`),
  CONSTRAINT `FK_notifications_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module: nurse-confirmed admission flag on ipd_admission.
ALTER TABLE `ipd_admission` ADD COLUMN `admission_confirmed` tinyint(1) NOT NULL DEFAULT '0';
ALTER TABLE `ipd_admission` ADD COLUMN `admission_confirmed_at` datetime(6) DEFAULT NULL;
ALTER TABLE `ipd_admission` ADD COLUMN `admitted_by_user_id` bigint DEFAULT NULL;

-- Nurse module: IPD admission form (one per admission).
CREATE TABLE `admission_forms` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `prn_no` varchar(60) DEFAULT NULL, `bed_no` varchar(60) DEFAULT NULL, `category` varchar(40) DEFAULT NULL,
  `patient_surname` varchar(100) DEFAULT NULL, `patient_first_name` varchar(100) DEFAULT NULL, `husband_father_name` varchar(150) DEFAULT NULL,
  `patient_address` text, `age` varchar(20) DEFAULT NULL, `sex` varchar(20) DEFAULT NULL, `occupation` varchar(100) DEFAULT NULL,
  `patient_category` varchar(40) DEFAULT NULL, `mediclaim` varchar(20) DEFAULT NULL, `tpa_name` varchar(200) DEFAULT NULL,
  `relative_name` varchar(150) DEFAULT NULL, `email` varchar(120) DEFAULT NULL, `telephone` varchar(40) DEFAULT NULL,
  `receptionist_name` varchar(120) DEFAULT NULL, `ref_dr` varchar(150) DEFAULT NULL,
  `ipd_registration_no` varchar(60) DEFAULT NULL, `department` varchar(120) DEFAULT NULL, `under_care_of_dr` varchar(150) DEFAULT NULL,
  `admitted_date` varchar(40) DEFAULT NULL, `admitted_time` varchar(40) DEFAULT NULL,
  `prov_diagnosis1` text, `prov_diagnosis2` text, `hypersensitivity_history` text,
  `relative_address` text, `relative_phone` varchar(40) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_admission_forms_public_id` (`public_id`),
  UNIQUE KEY `UK_admission_forms_ipd` (`ipd_admission_id`),
  KEY `idx_admission_forms_hospital` (`hospital_id`),
  CONSTRAINT `FK_admission_forms_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module: initial assessment (nurse-captured clinical fields).
CREATE TABLE `initial_assessments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `chief_complaints` text, `associated_illness` text, `relevant_investigations` text,
  `allergies` text, `vaccination_history` text, `others` text,
  `past_history` text, `family_history` text, `personal_history` text,
  `provisional_diagnosis` text, `care_plan` text,
  `pain_score` int DEFAULT NULL,
  `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_initial_assessments_public_id` (`public_id`),
  UNIQUE KEY `UK_initial_assessments_ipd` (`ipd_admission_id`),
  KEY `idx_initial_assessments_hospital` (`hospital_id`),
  CONSTRAINT `FK_initial_assessments_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module: vulnerability assessment (nurse-captured).
CREATE TABLE `vulnerability_assessments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `category` varchar(120) DEFAULT NULL, `fall_risk_assessment` text, `sensory_deficit` text,
  `disorientation` varchar(120) DEFAULT NULL, `self_care_deficit` varchar(10) DEFAULT NULL, `mobility_problem` varchar(10) DEFAULT NULL,
  `history_of_fall` varchar(10) DEFAULT NULL, `impaired_judgement` varchar(10) DEFAULT NULL,
  `psychological_status` varchar(200) DEFAULT NULL, `remarks` text, `nursing_intervention` text,
  `reason_for_transfer` text, `investigation_lab` text, `investigation_radiology` text,
  `transfer_provisional_diagnosis` text, `transfer_doctor_name` varchar(150) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_vuln_public_id` (`public_id`),
  UNIQUE KEY `UK_vuln_ipd` (`ipd_admission_id`),
  KEY `idx_vuln_hospital` (`hospital_id`),
  CONSTRAINT `FK_vuln_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nurse module: sugar chart entries (blood sugar + treatment).
CREATE TABLE `sugar_chart_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `nurse_user_id` bigint NOT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `blood_sugar` varchar(60) DEFAULT NULL,
  `treatment` text,
  `recorded_at` datetime(6) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_sugar_public_id` (`public_id`),
  KEY `idx_sugar_admission_time` (`ipd_admission_id`,`recorded_at`),
  KEY `idx_sugar_hospital` (`hospital_id`),
  CONSTRAINT `FK_sugar_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT module (Phase 2): surgeries (OT case lifecycle).
CREATE TABLE `surgeries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  -- NULL for a DAY_CARE procedure: the surgery is anchored on the patient, not an admission.
  `ipd_admission_id` bigint DEFAULT NULL,
  `encounter_type` varchar(20) NOT NULL DEFAULT 'IPD',
  `waitlist_priority` int NOT NULL DEFAULT '0',
  `target_date` date DEFAULT NULL,
  `approved_at` datetime(6) DEFAULT NULL,
  `ot_room_id` bigint DEFAULT NULL,
  `estimated_duration_minutes` int DEFAULT NULL,
  `patient_id` bigint NOT NULL,
  `procedure_name` varchar(255) DEFAULT NULL,
  `clinical_notes` text,
  `priority` varchar(20) DEFAULT NULL,
  `preferred_date` date DEFAULT NULL,
  `requested_by_doctor_id` bigint DEFAULT NULL,
  `requested_by_user_id` bigint DEFAULT NULL,
  `requested_at` datetime(6) NOT NULL,
  `status` varchar(20) NOT NULL,
  `lifecycle_version` bigint NOT NULL DEFAULT '0',
  `surgeon_doctor_id` bigint DEFAULT NULL,
  `surgeon_name` varchar(255) DEFAULT NULL,
  `anaesthetist_name` varchar(255) DEFAULT NULL,
  `scheduled_at` datetime(6) DEFAULT NULL,
  `ot_ward_id` bigint DEFAULT NULL,
  `ot_bed_id` bigint DEFAULT NULL,
  `scheduled_by_user_id` bigint DEFAULT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_surgery_public_id` (`public_id`),
  KEY `idx_surgery_hospital_status` (`hospital_id`,`status`),
  KEY `idx_surgery_admission` (`ipd_admission_id`),
  CONSTRAINT `FK_surgery_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Phase 2 — a hospital's OT permission grants, keyed on the role STRING.
-- Overrides only: zero rows for a hospital means "use OtPermissions.defaultsFor(role)".
CREATE TABLE `role_permissions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `role` varchar(30) NOT NULL,
  `permission_code` varchar(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_role_permission` (`hospital_id`,`role`,`permission_code`),
  KEY `idx_role_permission_hospital` (`hospital_id`),
  CONSTRAINT `FK_role_permission_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Phase 3 — append-only audit of every surgical case status change.
-- Every board metric (turnover, on-time start, cancellation rate by reason) queries this.
CREATE TABLE `surgery_state_transitions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `surgery_id` bigint NOT NULL,
  `from_status` varchar(20) DEFAULT NULL,
  `to_status` varchar(20) NOT NULL,
  `actor_user_id` bigint DEFAULT NULL,
  -- SYSTEM when a policy auto-satisfied the step; an approval nobody made must not read as one somebody made.
  `actor_kind` varchar(10) NOT NULL,
  `reason_code` varchar(60) DEFAULT NULL,
  `reason_text` varchar(255) DEFAULT NULL,
  `payload_json` text,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sst_surgery` (`surgery_id`,`created_at`),
  KEY `idx_sst_hospital_to` (`hospital_id`,`to_status`,`created_at`),
  CONSTRAINT `FK_sst_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT 4.6A — immutable anaesthesia-clearance decisions and explicit emergency bypasses.
CREATE TABLE `surgery_anaesthesia_clearances` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `surgery_id` bigint NOT NULL,
  `hospital_id` bigint NOT NULL,
  `outcome` varchar(40) NOT NULL,
  `conditions_comments` text,
  `recorded_by_user_id` bigint NOT NULL,
  `recorded_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sac_hospital_surgery_time` (`hospital_id`,`surgery_id`,`recorded_at`),
  KEY `idx_sac_surgery` (`surgery_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `surgery_emergency_overrides` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `surgery_id` bigint NOT NULL,
  `hospital_id` bigint NOT NULL,
  `reason` text NOT NULL,
  `bypassed_gates` varchar(100) NOT NULL,
  `recorded_by_user_id` bigint NOT NULL,
  `recorded_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_seo_hospital_surgery_time` (`hospital_id`,`surgery_id`,`recorded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Phase 4 — an operation theatre as a first-class resource (not a ward named "OT").
CREATE TABLE `ot_rooms` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `name` varchar(100) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'AVAILABLE',
  `current_surgery_id` bigint DEFAULT NULL,
  `turnover_minutes` int NOT NULL DEFAULT '15',
  `source_ward_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_ot_room_public_id` (`public_id`),
  UNIQUE KEY `uk_ot_room_name` (`hospital_id`,`name`),
  CONSTRAINT `FK_ot_room_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Phase 5 — per-hospital workflow policy overrides. Absent row = built-in default.
CREATE TABLE `ot_workflow_policies` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `policy_key` varchar(40) NOT NULL,
  `priority_scope` varchar(10) NOT NULL DEFAULT 'ANY',
  `value` varchar(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ot_policy` (`hospital_id`,`policy_key`,`priority_scope`),
  KEY `idx_ot_policy_hospital` (`hospital_id`),
  CONSTRAINT `FK_ot_policy_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Phase 6 — the surgical team, and a hospital's custom case roles.
CREATE TABLE `case_roles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `code` varchar(40) NOT NULL,
  `label` varchar(100) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_case_role` (`hospital_id`,`code`),
  CONSTRAINT `FK_case_role_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `surgery_team_members` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `surgery_id` bigint NOT NULL,
  `case_role_code` varchar(40) NOT NULL,
  -- Exactly one of user_id / external_name is set. external_name is the legitimate
  -- fallback for an operator with no login (mirrors surgeries.surgeon_name).
  `user_id` bigint DEFAULT NULL,
  `external_name` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_team_surgery` (`surgery_id`),
  CONSTRAINT `FK_team_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Phase 7 — WHO Surgical Safety Checklist (phases as signed columns) + milestones.
CREATE TABLE `who_checklists` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `surgery_id` bigint NOT NULL,
  `sign_in_at` datetime(6) DEFAULT NULL, `sign_in_by_user_id` bigint DEFAULT NULL,
  `time_out_at` datetime(6) DEFAULT NULL, `time_out_by_user_id` bigint DEFAULT NULL,
  `sign_out_at` datetime(6) DEFAULT NULL, `sign_out_by_user_id` bigint DEFAULT NULL,
  `site_marked` tinyint(1) DEFAULT NULL, `counts_correct` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_who_surgery` (`surgery_id`),
  CONSTRAINT `FK_who_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `surgery_milestones` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `surgery_id` bigint NOT NULL,
  `milestone` varchar(30) NOT NULL,
  `occurred_at` datetime(6) NOT NULL,
  `recorded_by_user_id` bigint DEFAULT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_milestone_surgery` (`surgery_id`,`occurred_at`),
  CONSTRAINT `FK_milestone_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Phase 8 — PACU recovery. Never a case state: the theatre is free while the patient recovers.
CREATE TABLE `ot_recovery_episodes` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `surgery_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `arrived_at` datetime(6) NOT NULL,
  `discharged_at` datetime(6) DEFAULT NULL,
  `transfer_destination` varchar(20) DEFAULT NULL,
  `arrived_by_user_id` bigint DEFAULT NULL,
  `discharged_by_user_id` bigint DEFAULT NULL,
  `recovery_bay_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_recovery_surgery` (`surgery_id`),
  CONSTRAINT `FK_recovery_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT-P0B — a recovery bay is the smallest additive location representation: occupancy is
-- derived from whether an undischarged ot_recovery_episodes row currently references it, never
-- an ot_rooms row (a theatre is freed the moment its case COMPLETEs; recovery is separate).
-- INV-2/INV-3 — batch-aware Hospital/Clinic medicine stock. Different batch numbers / expiries
-- stay distinct rows; availability is SUM(current_quantity) over active, unexpired batches.
CREATE TABLE `medicine_stock_batches` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(36) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `medicine_id` bigint NOT NULL,
  `batch_number` varchar(100) NOT NULL,
  `expiry_date` date NOT NULL,
  `received_quantity` int NOT NULL DEFAULT '0',
  `current_quantity` int NOT NULL DEFAULT '0',
  `unit_price` double DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `received_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_medicine_stock_batch_public_id` (`public_id`),
  UNIQUE KEY `uk_medicine_batch` (`hospital_id`,`medicine_id`,`batch_number`),
  KEY `idx_medicine_batch_fefo` (`hospital_id`,`medicine_id`,`expiry_date`),
  CONSTRAINT `FK_medicine_batch_medicine` FOREIGN KEY (`medicine_id`) REFERENCES `medicines` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_medicine_batch_qty_non_negative` CHECK ((`current_quantity` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Append-only ledger for every Hospital/Clinic stock change. Never updated, never deleted --
-- corrections are compensating movements.
CREATE TABLE `stock_movements` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(36) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `inventory_domain` varchar(20) NOT NULL,
  `item_id` bigint NOT NULL,
  `batch_id` bigint DEFAULT NULL,
  `movement_type` varchar(30) NOT NULL,
  `direction` varchar(3) NOT NULL,
  `quantity` int NOT NULL,
  `balance_after` int DEFAULT NULL,
  `reference_type` varchar(40) DEFAULT NULL,
  `reference_id` bigint DEFAULT NULL,
  `idempotency_key` varchar(100) DEFAULT NULL,
  `performed_by_user_id` bigint DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stock_movement_public_id` (`public_id`),
  UNIQUE KEY `uk_stock_movement_idempotency` (`hospital_id`,`idempotency_key`,`batch_id`),
  KEY `idx_stock_movement_item` (`hospital_id`,`inventory_domain`,`item_id`,`id`),
  KEY `idx_stock_movement_batch` (`hospital_id`,`batch_id`,`id`),
  CONSTRAINT `ck_stock_movement_qty_positive` CHECK ((`quantity` > 0)),
  CONSTRAINT `ck_stock_movement_direction` CHECK ((`direction` in (_utf8mb4'IN',_utf8mb4'OUT')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `recovery_bays` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(36) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `name` varchar(100) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_recovery_bay_public_id` (`public_id`),
  UNIQUE KEY `uk_recovery_bay_name` (`hospital_id`,`name`),
  CONSTRAINT `FK_recovery_bay_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ot_recovery_observations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `episode_id` bigint NOT NULL,
  `observed_at` datetime(6) NOT NULL,
  `aldrete_score` int DEFAULT NULL,
  `recorded_by_user_id` bigint DEFAULT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_recovery_obs_episode` (`episode_id`,`observed_at`),
  CONSTRAINT `FK_recovery_obs_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Phase 9 — the theatre occupancy timeline (utilisation & turnover from real spans).
CREATE TABLE `ot_room_occupancy` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hospital_id` bigint NOT NULL,
  `ot_room_id` bigint NOT NULL,
  `surgery_id` bigint NOT NULL,
  `occupied_from` datetime(6) NOT NULL,
  `occupied_to` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_occupancy_room` (`ot_room_id`,`occupied_from`),
  KEY `idx_occupancy_hospital` (`hospital_id`,`occupied_from`),
  CONSTRAINT `FK_occupancy_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `surgery_forms` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `ipd_admission_id` bigint DEFAULT NULL,
  `surgery_id` bigint DEFAULT NULL,
  `form_type` varchar(60) NOT NULL,
  `data_json` longtext,
  `saved_by_user_id` bigint DEFAULT NULL,
  `performed_by_nurse_id` bigint DEFAULT NULL,
  `recorded_by_user_id` bigint DEFAULT NULL,
  `version` int NOT NULL DEFAULT '1',
  -- TRUE for the live row, NULL once superseded. Never FALSE: the unique key below
  -- relies on MySQL treating NULLs as distinct so superseded versions can coexist.
  `is_current` tinyint(1) DEFAULT '1',
  `signed_at` datetime(6) DEFAULT NULL,
  `signed_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_surgery_form_public_id` (`public_id`),
  -- Scoped to the PROCEDURE, not the admission: two surgeries in one admission each
  -- keep their own signed consent and WHO checklist.
  UNIQUE KEY `UK_surgery_form_surgery_type` (`surgery_id`,`form_type`,`is_current`),
  KEY `idx_surgery_form_hospital` (`hospital_id`),
  CONSTRAINT `FK_surgery_form_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nursing Mgmt Phase B1 — reusable nurse shift definitions
CREATE TABLE `shift_templates` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `name` varchar(60) NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_shift_template_public` (`public_id`),
  KEY `idx_shift_template_hospital` (`hospital_id`),
  CONSTRAINT `FK_shift_template_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nursing Mgmt Phase B1 — bookable appointment slot definitions
CREATE TABLE `appointment_slots` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_appt_slot_public` (`public_id`),
  KEY `idx_appt_slot_hospital` (`hospital_id`),
  CONSTRAINT `FK_appt_slot_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nursing Mgmt Phase B2 — nurse shift schedules (snapshots template times per date)
CREATE TABLE `nurse_shift_schedules` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `nurse_profile_id` bigint NOT NULL,
  `ward_id` bigint DEFAULT NULL,
  `shift_date` date NOT NULL,
  `shift_template_id` bigint NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_nss_public` (`public_id`),
  UNIQUE KEY `UK_nss_nurse_date` (`nurse_profile_id`,`shift_date`),
  KEY `idx_nss_hospital_date` (`hospital_id`,`shift_date`),
  KEY `idx_nss_ward_date` (`ward_id`,`shift_date`),
  CONSTRAINT `FK_nss_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nursing Mgmt Phase D — daily nurse attendance
CREATE TABLE `nurse_attendance` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `nurse_profile_id` bigint NOT NULL,
  `ward_id` bigint DEFAULT NULL,
  `attendance_date` date NOT NULL,
  `status` varchar(20) NOT NULL,
  `shift_template_id` bigint DEFAULT NULL,
  `shift_start_time` time DEFAULT NULL,
  `shift_end_time` time DEFAULT NULL,
  `check_in_time` time DEFAULT NULL,
  `check_out_time` time DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `marked_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_na_public` (`public_id`),
  UNIQUE KEY `UK_na_nurse_date` (`nurse_profile_id`,`attendance_date`),
  KEY `idx_na_hospital_date` (`hospital_id`,`attendance_date`),
  KEY `idx_na_ward_date` (`ward_id`,`attendance_date`),
  CONSTRAINT `FK_na_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nursing Mgmt Phase F — temporary ward assignment + nurse substitution
CREATE TABLE `nurse_ward_assignments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `nurse_profile_id` bigint NOT NULL,
  `temp_ward_id` bigint NOT NULL,
  `from_date` date NOT NULL,
  `to_date` date NOT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_nwa_public` (`public_id`),
  KEY `idx_nwa_nurse` (`nurse_profile_id`,`from_date`,`to_date`),
  KEY `idx_nwa_ward` (`temp_ward_id`,`from_date`,`to_date`),
  KEY `idx_nwa_hospital` (`hospital_id`,`to_date`),
  CONSTRAINT `FK_nwa_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `nurse_substitutions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `primary_nurse_profile_id` bigint NOT NULL,
  `replacement_nurse_profile_id` bigint NOT NULL,
  `from_date` date NOT NULL,
  `to_date` date NOT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_nsub_public` (`public_id`),
  KEY `idx_nsub_repl` (`replacement_nurse_profile_id`,`from_date`,`to_date`),
  KEY `idx_nsub_hospital` (`hospital_id`,`to_date`),
  CONSTRAINT `FK_nsub_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Hospital calendar events (Nursing Mgmt Phase G)
CREATE TABLE IF NOT EXISTS calendar_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(64) NOT NULL UNIQUE,
    hospital_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    description VARCHAR(500),
    created_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_calevent_hosp_dates (hospital_id, from_date, to_date),
    CONSTRAINT fk_calevent_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id) ON DELETE CASCADE
);

-- Per-hospital OPD vitals config: built-in overrides + custom vitals
CREATE TABLE IF NOT EXISTS hospital_vitals (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(64) NOT NULL UNIQUE,
    hospital_id BIGINT NOT NULL,
    vital_key VARCHAR(60) NOT NULL,
    label VARCHAR(60) NOT NULL,
    unit VARCHAR(20),
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    is_custom TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_hosp_vital (hospital_id, vital_key),
    CONSTRAINT fk_hosp_vital_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id) ON DELETE CASCADE
);

-- Per-hospital clinical form availability + edit access (Files & Access, Phase 1)
CREATE TABLE IF NOT EXISTS hospital_form_access (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hospital_id BIGINT NOT NULL,
    form_key VARCHAR(60) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    access_role VARCHAR(10) NOT NULL DEFAULT 'BOTH',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_form_access_hosp_key (hospital_id, form_key),
    CONSTRAINT fk_form_access_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id) ON DELETE CASCADE
);

-- Nursing Mgmt Phase C1 — bed status change audit trail
CREATE TABLE `bed_status_audits` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(255) NOT NULL,
  `hospital_id` bigint NOT NULL,
  `bed_id` bigint NOT NULL,
  `ward_id` bigint DEFAULT NULL,
  `previous_status` varchar(20) DEFAULT NULL,
  `new_status` varchar(20) NOT NULL,
  `changed_by_user_id` bigint DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `changed_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_bsa_public` (`public_id`),
  KEY `idx_bsa_bed_time` (`bed_id`,`changed_at`),
  KEY `idx_bsa_hospital` (`hospital_id`),
  CONSTRAINT `FK_bsa_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- OT Incharge profiles table
CREATE TABLE `ot_incharges` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` varchar(64) NOT NULL UNIQUE,
  `hospital_id` bigint NOT NULL,
  `name` varchar(100) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `email` varchar(100) NOT NULL,
  `age` int DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_ot_incharges_hospital` FOREIGN KEY (`hospital_id`) REFERENCES `hospitals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
