package com.hms.service.documents;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.UUID;

/**
 * The only class that touches the filesystem for patient documents.
 *
 * <p>Files are laid out per hospital, and the stored name is always generated. Keeping every path
 * decision here means the traversal guard is provable by reading one file, rather than by auditing
 * every caller that might one day pass a name through from a request.
 */
@Component
public class DocumentStorage {

    private static final Logger log = LoggerFactory.getLogger(DocumentStorage.class);

    @Value("${hms.documents.dir:/var/hms/patient-documents}")
    private String baseDir;

    /** @return the generated filename to record on the document row. */
    public String store(Long hospitalId, MultipartFile file, String extension) {
        String stored = UUID.randomUUID() + "." + extension;
        Path target = resolve(hospitalId, stored);
        try {
            Files.createDirectories(target.getParent());
            try (InputStream in = file.getInputStream()) {
                Files.copy(in, target);
            }
            restrictPermissions(target);
            return stored;
        } catch (IOException e) {
            // A failed copy writes straight to the final path, so a disk-full or dropped
            // connection leaves a truncated file behind. store() throws before returning, so no
            // document row is ever created for it — the fragment would be referenced by nothing,
            // served by nothing, and removed by nothing, because there is no cleanup job.
            try {
                Files.deleteIfExists(target);
            } catch (IOException cleanup) {
                log.warn("Could not remove the partial file {}: {}", target, cleanup.getMessage());
            }
            // The raw message routinely carries the absolute on-disk path, and GlobalExceptionHandler
            // puts it straight into the response the browser shows. Logged, never handed out.
            log.warn("Could not save document for hospital {}: {}", hospitalId, e.getMessage());
            throw new IllegalArgumentException("The file could not be saved. Please try again.");
        }
    }

    /**
     * Opens the stored file for streaming.
     *
     * <p><b>The caller owns the returned stream and must close it.</b> Today's only caller hands it
     * to Spring's {@code InputStreamResource}, which closes it after the response is written.
     */
    public InputStream read(Long hospitalId, String storedFilename) {
        Path path = resolve(hospitalId, storedFilename);
        if (!Files.exists(path)) {
            throw new IllegalArgumentException(
                    "This document is recorded but its file is no longer on the server.");
        }
        try {
            return Files.newInputStream(path);
        } catch (IOException e) {
            log.warn("Could not open document {} for hospital {}: {}",
                    storedFilename, hospitalId, e.getMessage());
            throw new IllegalArgumentException("The file could not be opened. Please try again.");
        }
    }

    /** Removing a file that is already gone is success, not an error. */
    public void delete(Long hospitalId, String storedFilename) {
        try {
            Files.deleteIfExists(resolve(hospitalId, storedFilename));
        } catch (IOException e) {
            log.warn("Could not delete document file {}: {}", storedFilename, e.getMessage());
        }
    }

    /**
     * Builds the path and refuses anything that would leave the hospital's folder.
     *
     * <p>A stored name is generated by this class, so in normal operation it is safe. The check
     * exists because "it can only ever hold a UUID" is an assumption about every future caller, and
     * traversal is not the kind of bug worth leaving to an assumption.
     */
    private Path resolve(Long hospitalId, String storedFilename) {
        if (storedFilename == null || storedFilename.isBlank()
                || storedFilename.contains("/") || storedFilename.contains("\\")
                || storedFilename.contains("..")
                // A NUL otherwise survives every check above and only fails inside resolve(),
                // producing the wrong message by a different route.
                || storedFilename.indexOf('\0') >= 0) {
            throw new IllegalArgumentException("Invalid document reference.");
        }
        Path hospitalDir = Paths.get(baseDir).toAbsolutePath().normalize()
                .resolve(String.valueOf(hospitalId));
        Path target = hospitalDir.resolve(storedFilename).normalize();

        // Must be a file directly INSIDE the hospital's directory, not merely somewhere under it.
        //
        // startsWith alone was not enough: "." is not blank and contains none of the characters
        // rejected above, yet hospitalDir.resolve(".").normalize() reduces to hospitalDir itself
        // and so passed. That made delete(id, ".") a call to delete the hospital's whole document
        // directory. Comparing the parent pins the result to one level down, where a real
        // document always lives.
        if (!hospitalDir.equals(target.getParent())) {
            throw new IllegalArgumentException("Invalid document reference.");
        }
        return target;
    }

    /**
     * Narrows the file to the owning user. Best effort by necessity — not every filesystem honours
     * these — but a failure is logged rather than swallowed, because the difference between
     * "restricted" and "world-readable" on a file holding patient data is worth knowing about.
     */
    private void restrictPermissions(Path target) {
        try {
            java.io.File f = target.toFile();
            // These return false on failure instead of throwing, so ignoring the result means a
            // filesystem that refuses them leaves the file readable by anyone, silently.
            boolean ok = f.setReadable(false, false)
                    & f.setReadable(true, true)
                    & f.setWritable(false, false)
                    & f.setWritable(true, true);
            if (!ok) {
                log.warn("Could not fully restrict permissions on {} — the file may be readable "
                        + "by other users on this host", target);
            }
        } catch (SecurityException e) {
            log.warn("Could not restrict permissions on {}: {}", target, e.getMessage());
        }
    }
}
