package com.hms.service.documents;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.UUID;

/**
 * The only class that touches the filesystem for patient documents.
 *
 * <p>Files are laid out per hospital, and the stored name is always generated. Keeping every path
 * decision here means the traversal guard is provable by reading one file, rather than by auditing
 * every caller that might one day pass a name through from a request.
 */
@Component
public class DocumentStorage {

    private static final Logger log = LoggerFactory.getLogger(DocumentStorage.class);

    @Value("${hms.documents.dir:/var/hms/patient-documents}")
    private String baseDir;

    /** @return the generated filename to record on the document row. */
    public String store(Long hospitalId, MultipartFile file, String extension) {
        String stored = UUID.randomUUID() + "." + extension;
        Path target = resolve(hospitalId, stored);
        try {
            Files.createDirectories(target.getParent());
            try (InputStream in = file.getInputStream()) {
                Files.copy(in, target);
            }
            restrictPermissions(target);
            return stored;
        } catch (IOException e) {
            throw new IllegalArgumentException("Could not save the file: " + e.getMessage());
        }
    }

    public InputStream read(Long hospitalId, String storedFilename) {
        Path path = resolve(hospitalId, storedFilename);
        if (!Files.exists(path)) {
            throw new IllegalArgumentException(
                    "This document is recorded but its file is no longer on the server.");
        }
        try {
            return Files.newInputStream(path);
        } catch (IOException e) {
            throw new IllegalArgumentException("Could not open the file: " + e.getMessage());
        }
    }

    /** Removing a file that is already gone is success, not an error. */
    public void delete(Long hospitalId, String storedFilename) {
        try {
            Files.deleteIfExists(resolve(hospitalId, storedFilename));
        } catch (IOException e) {
            log.warn("Could not delete document file {}: {}", storedFilename, e.getMessage());
        }
    }

    /**
     * Builds the path and refuses anything that would leave the hospital's folder.
     *
     * <p>A stored name is generated by this class, so in normal operation it is safe. The check
     * exists because "it can only ever hold a UUID" is an assumption about every future caller, and
     * traversal is not the kind of bug worth leaving to an assumption.
     */
    private Path resolve(Long hospitalId, String storedFilename) {
        if (storedFilename == null || storedFilename.isBlank()
                || storedFilename.contains("/") || storedFilename.contains("\\")
                || storedFilename.contains("..")) {
            throw new IllegalArgumentException("Invalid document reference.");
        }
        Path hospitalDir = Paths.get(baseDir).toAbsolutePath().normalize()
                .resolve(String.valueOf(hospitalId));
        Path target = hospitalDir.resolve(storedFilename).normalize();
        if (!target.startsWith(hospitalDir)) {
            throw new IllegalArgumentException("Invalid document reference.");
        }
        return target;
    }

    /** Best effort: the file is patient data, so it should not be world-readable. */
    private void restrictPermissions(Path target) {
        try {
            target.toFile().setReadable(false, false);
            target.toFile().setReadable(true, true);
            target.toFile().setWritable(false, false);
            target.toFile().setWritable(true, true);
        } catch (SecurityException e) {
            log.warn("Could not restrict permissions on {}: {}", target, e.getMessage());
        }
    }
}
